Bug/arth
MaximilianSoerenPollak/todotui pull request #16
Opened 2023-02-15 03:00 UTC by probablyArth

2023-02-15 03:01 UTC, probablyArth commented
solves #9

2023-02-15 09:30 UTC, MaximilianSoerenPollak reviewed
Just left some comments with questions. But other than those looks good.

2023-02-15 09:30 UTC, MaximilianSoerenPollak commented on output.txt
> +
Not quite sure if this was an intentional upload, if so what is it for?
If it was accidental, please remove.

2023-02-15 09:30 UTC, MaximilianSoerenPollak commented on models/tui.go
> -				return m, cmd
What was the rational behind reversing the split up again? Was it too convoluted?
Can you explain the thought process?

2023-02-15 14:48 UTC, MaximilianSoerenPollak requested changes
Nice, if you could just remove the unwatned .txt file as well then this is GTM.

2023-02-16 17:32 UTC, MaximilianSoerenPollak approved these changes
Looks good.

LGTM :)

2023-02-16 17:33 UTC, merged